import { useState, useEffect, useMemo, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import { 
  Plus, Search, Edit, Trash2, X, 
  CheckCircle, Clock, AlertTriangle, FileText,
  Upload, FileCheck, Eye, History, Loader2
} from 'lucide-react'
import PageHeader from '../components/PageHeader'
import DataTable, { Column } from '../components/DataTable'
import DatePicker from '../components/DatePicker'
import { getApiBaseUrl } from '../utils/api'

const API_BASE = getApiBaseUrl()

interface Contract {
  id: string
  contractNumber: string
  contractName: string
  customerId: string
  customerName: string
  contractType: string
  contractAmount: number
  currency: string
  startDate: string | null
  endDate: string | null
  signDate: string | null
  status: string
  // 签署相关字段
  signStatus: string  // unsigned, pending_sign, signed, rejected
  signedFilePath: string | null
  signedFileName: string | null
  signedAt: string | null
  signedBy: number | null
  signedByName: string | null
  autoGenerated: boolean
  terms: string
  notes: string
  createTime: string
}

interface Customer {
  id: string
  customerName: string
}

interface SignHistory {
  id: number
  contractId: string
  action: string
  actionName: string
  operatorName: string
  oldStatus: string | null
  newStatus: string
  remark: string | null
  createTime: string
}

export default function CRMContracts() {
  const navigate = useNavigate()
  const [contracts, setContracts] = useState<Contract[]>([])
  const [customers, setCustomers] = useState<Customer[]>([])
  const [loading, setLoading] = useState(true)
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(20)
  const [searchValue, setSearchValue] = useState('')
  const [filterStatus, setFilterStatus] = useState<string>('')
  const [showModal, setShowModal] = useState(false)
  const [editingItem, setEditingItem] = useState<Contract | null>(null)
  const [formData, setFormData] = useState({
    contractName: '',
    customerId: '',
    customerName: '',
    contractType: 'service',
    contractAmount: 0,
    currency: 'EUR',
    startDate: '',
    endDate: '',
    signDate: '',
    terms: '',
    notes: ''
  })
  
  // 签署相关状态
  const [showUploadModal, setShowUploadModal] = useState(false)
  const [uploadingContract, setUploadingContract] = useState<Contract | null>(null)
  const [uploading, setUploading] = useState(false)
  const [showHistoryModal, setShowHistoryModal] = useState(false)
  const [signHistory, setSignHistory] = useState<SignHistory[]>([])
  const [historyLoading, setHistoryLoading] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)

   
  useEffect(() => {
    loadData()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page, pageSize, searchValue, filterStatus])

  const loadData = async () => {
    setLoading(true)
    try {
      const params = new URLSearchParams({
        page: page.toString(),
        pageSize: pageSize.toString()
      })
      if (searchValue) params.append('search', searchValue)
      if (filterStatus) params.append('status', filterStatus)

      const [contractRes, custRes] = await Promise.all([
        fetch(`${API_BASE}/api/contracts?${params}`),
        fetch(`${API_BASE}/api/customers?pageSize=100`)
      ])

      const [contractData, custData] = await Promise.all([
        contractRes.json(),
        custRes.json()
      ])
      
      if (contractData.errCode === 200) {
        setContracts(contractData.data.list || [])
        setTotal(contractData.data.total || 0)
      }
      if (custData.errCode === 200) setCustomers(custData.data.list || [])
    } catch (error) {
      console.error('加载数据失败:', error)
    } finally {
      setLoading(false)
    }
  }

  const handleOpenModal = (item?: Contract) => {
    if (item) {
      setEditingItem(item)
      setFormData({
        contractName: item.contractName,
        customerId: item.customerId || '',
        customerName: item.customerName || '',
        contractType: item.contractType || 'service',
        contractAmount: item.contractAmount,
        currency: item.currency || 'EUR',
        startDate: item.startDate || '',
        endDate: item.endDate || '',
        signDate: item.signDate || '',
        terms: item.terms || '',
        notes: item.notes || ''
      })
    } else {
      setEditingItem(null)
      setFormData({
        contractName: '',
        customerId: '',
        customerName: '',
        contractType: 'service',
        contractAmount: 0,
        currency: 'EUR',
        startDate: '',
        endDate: '',
        signDate: '',
        terms: '',
        notes: ''
      })
    }
    setShowModal(true)
  }

  const handleSubmit = async () => {
    if (!formData.contractName) {
      alert('请输入合同名称')
      return
    }
    if (!formData.customerName && !formData.customerId) {
      alert('请选择客户')
      return
    }

    try {
      const url = editingItem 
        ? `/api/contracts/${editingItem.id}`
        : '/api/contracts'
      const method = editingItem ? 'PUT' : 'POST'

      const response = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData)
      })

      const data = await response.json()
      if (data.errCode === 200) {
        setShowModal(false)
        loadData()
      } else {
        alert(data.msg || '操作失败')
      }
    } catch (error) {
      console.error('保存失败:', error)
      alert('保存失败')
    }
  }

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const handleUpdateStatus = async (id: string, status: string) => {
    try {
      const response = await fetch(`${API_BASE}/api/contracts/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status })
      })
      const data = await response.json()
      if (data.errCode === 200) {
        loadData()
      }
    } catch (error) {
      console.error('更新状态失败:', error)
    }
  }

  const handleDelete = async (item: Contract) => {
    if (!confirm(`确定要删除合同"${item.contractName}"吗？`)) return

    try {
      const response = await fetch(`${API_BASE}/api/contracts/${item.id}`, {
        method: 'DELETE'
      })
      const data = await response.json()
      if (data.errCode === 200) {
        loadData()
      } else {
        alert(data.msg || '删除失败')
      }
    } catch (error) {
      console.error('删除失败:', error)
    }
  }

  const formatCurrency = (value: number, currency = 'EUR') => {
    return new Intl.NumberFormat('de-DE', { style: 'currency', currency }).format(value)
  }

  const getStatusInfo = (status: string) => {
    const statusMap: Record<string, { label: string; icon: any; color: string; bg: string }> = {
      draft: { label: '草稿', icon: FileText, color: 'text-gray-600', bg: 'bg-gray-100' },
      pending: { label: '待签署', icon: Clock, color: 'text-amber-600', bg: 'bg-amber-100' },
      active: { label: '生效中', icon: CheckCircle, color: 'text-green-600', bg: 'bg-green-100' },
      expired: { label: '已过期', icon: AlertTriangle, color: 'text-orange-600', bg: 'bg-orange-100' },
      terminated: { label: '已终止', icon: AlertTriangle, color: 'text-red-600', bg: 'bg-red-100' }
    }
    return statusMap[status] || statusMap.draft
  }

  // 获取签署状态信息
  const getSignStatusInfo = (signStatus: string) => {
    const statusMap: Record<string, { label: string; icon: any; color: string; bg: string }> = {
      unsigned: { label: '未签署', icon: FileText, color: 'text-gray-500', bg: 'bg-gray-100' },
      pending_sign: { label: '待签署', icon: Clock, color: 'text-amber-600', bg: 'bg-amber-100' },
      signed: { label: '已签署', icon: FileCheck, color: 'text-green-600', bg: 'bg-green-100' },
      rejected: { label: '已拒签', icon: AlertTriangle, color: 'text-red-600', bg: 'bg-red-100' }
    }
    return statusMap[signStatus] || statusMap.unsigned
  }

  // 打开上传签署合同弹窗
  const handleOpenUploadModal = (contract: Contract) => {
    setUploadingContract(contract)
    setShowUploadModal(true)
  }

  // 上传已签署合同
  const handleUploadSignedContract = async (file: File) => {
    if (!uploadingContract) return
    
    setUploading(true)
    try {
      // 1. 先上传文件
      const formData = new FormData()
      formData.append('file', file)
      formData.append('type', 'contract')
      formData.append('contractId', uploadingContract.id)
      
      const uploadRes = await fetch(`${API_BASE}/api/upload`, {
        method: 'POST',
        body: formData
      })
      const uploadData = await uploadRes.json()
      
      if (uploadData.errCode !== 200) {
        throw new Error(uploadData.msg || '文件上传失败')
      }
      
      // 2. 更新合同签署状态
      const updateRes = await fetch(`${API_BASE}/api/contracts/${uploadingContract.id}/upload-signed`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          filePath: uploadData.data.path || uploadData.data.url,
          fileName: file.name
        })
      })
      const updateData = await updateRes.json()
      
      if (updateData.errCode === 200) {
        alert('合同签署成功！')
        setShowUploadModal(false)
        setUploadingContract(null)
        loadData()
      } else {
        throw new Error(updateData.msg || '更新签署状态失败')
      }
    } catch (error: any) {
      console.error('上传签署合同失败:', error)
      alert(error.message || '上传失败')
    } finally {
      setUploading(false)
    }
  }

  // 查看签署历史
  const handleViewSignHistory = async (contract: Contract) => {
    setUploadingContract(contract)
    setHistoryLoading(true)
    setShowHistoryModal(true)
    
    try {
      const res = await fetch(`${API_BASE}/api/contracts/${contract.id}/sign-history`)
      const data = await res.json()
      if (data.errCode === 200) {
        setSignHistory(data.data || [])
      }
    } catch (error) {
      console.error('获取签署历史失败:', error)
    } finally {
      setHistoryLoading(false)
    }
  }

  const getTypeLabel = (type: string) => {
    const types: Record<string, string> = {
      service: '服务合同',
      sales: '销售合同',
      purchase: '采购合同',
      cooperation: '合作协议',
      other: '其他'
    }
    return types[type] || type
  }

  const columns: Column<Contract>[] = useMemo(() => [
    {
      key: 'contractNumber',
      label: '合同编号',
      width: 140,
      sorter: true,
      render: (_value, record) => (
        <div>
        <span className="text-primary-600 font-medium text-xs">{record.contractNumber}</span>
          {record.autoGenerated && (
            <span className="ml-1 px-1 py-0.5 text-[9px] bg-blue-100 text-blue-600 rounded">自动生成</span>
          )}
        </div>
      )
    },
    {
      key: 'contractName',
      label: '合同名称',
      width: 180,
      sorter: true,
      filterable: true,
      render: (_value, record) => (
        <div>
          <div className="font-medium text-gray-900 text-xs line-clamp-1">{record.contractName}</div>
          <div className="text-[10px] text-gray-500">{record.customerName || '-'}</div>
        </div>
      )
    },
    {
      key: 'contractType',
      label: '类型',
      width: 90,
      sorter: true,
      filters: [
        { text: '服务合同', value: 'service' },
        { text: '销售合同', value: 'sales' },
        { text: '采购合同', value: 'purchase' },
        { text: '合作协议', value: 'cooperation' },
        { text: '其他', value: 'other' },
      ],
      onFilter: (value, record) => record.contractType === value,
      render: (_value, record) => (
        <span className="text-xs text-gray-600">{getTypeLabel(record.contractType)}</span>
      )
    },
    {
      key: 'contractAmount',
      label: '合同金额',
      width: 120,
      sorter: (a, b) => a.contractAmount - b.contractAmount,
      render: (_value, record) => (
        <span className="text-xs font-medium text-gray-900">
          {formatCurrency(record.contractAmount, record.currency)}
        </span>
      )
    },
    {
      key: 'signStatus',
      label: '签署状态',
      width: 100,
      sorter: true,
      filters: [
        { text: '未签署', value: 'unsigned' },
        { text: '待签署', value: 'pending_sign' },
        { text: '已签署', value: 'signed' },
        { text: '已拒签', value: 'rejected' },
      ],
      onFilter: (value, record) => record.signStatus === value,
      render: (_value, record) => {
        const info = getSignStatusInfo(record.signStatus)
        const Icon = info.icon
        return (
          <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-medium ${info.bg} ${info.color}`}>
            <Icon className="w-3 h-3" />
            {info.label}
          </span>
        )
      }
    },
    {
      key: 'signInfo',
      label: '签署信息',
      width: 140,
      sorter: (a, b) => {
        const dateA = a.signedAt ? new Date(a.signedAt).getTime() : 0
        const dateB = b.signedAt ? new Date(b.signedAt).getTime() : 0
        return dateA - dateB
      },
      render: (_value, record) => (
        <div className="text-xs">
          {record.signStatus === 'signed' ? (
            <div>
              <div className="text-gray-700">{record.signedByName || '-'}</div>
              <div className="text-[10px] text-gray-400">
                {record.signedAt ? new Date(record.signedAt).toLocaleDateString('zh-CN') : '-'}
              </div>
            </div>
          ) : (
            <span className="text-gray-400">-</span>
          )}
        </div>
      )
    },
    {
      key: 'status',
      label: '合同状态',
      width: 90,
      sorter: true,
      filters: [
        { text: '草稿', value: 'draft' },
        { text: '待签署', value: 'pending' },
        { text: '生效中', value: 'active' },
        { text: '已过期', value: 'expired' },
        { text: '已终止', value: 'terminated' },
      ],
      onFilter: (value, record) => record.status === value,
      render: (_value, record) => {
        const info = getStatusInfo(record.status)
        const Icon = info.icon
        return (
          <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-medium ${info.bg} ${info.color}`}>
            <Icon className="w-3 h-3" />
            {info.label}
          </span>
        )
      }
    },
    {
      key: 'actions',
      label: '操作',
      width: 220,
      render: (_value, record) => (
        <div className="flex items-center gap-1">
          {/* 待签署状态：显示上传按钮 */}
          {record.signStatus === 'pending_sign' && (
            <button
              onClick={() => handleOpenUploadModal(record)}
              className="px-2 py-1 text-[10px] bg-primary-50 text-primary-600 rounded hover:bg-primary-100 flex items-center gap-1"
            >
              <Upload className="w-3 h-3" />
              上传签署
            </button>
          )}
          {/* 已签署：显示查看按钮 */}
          {record.signStatus === 'signed' && record.signedFilePath && (
            <a
              href={record.signedFilePath}
              target="_blank"
              rel="noopener noreferrer"
              className="px-2 py-1 text-[10px] bg-green-50 text-green-600 rounded hover:bg-green-100 flex items-center gap-1"
            >
              <Eye className="w-3 h-3" />
              查看
            </a>
          )}
          {/* 签署历史 */}
            <button
            onClick={() => handleViewSignHistory(record)}
            className="p-1 hover:bg-gray-100 rounded text-gray-500"
            title="签署历史"
          >
            <History className="w-3.5 h-3.5" />
            </button>
          {/* 编辑（未签署才能编辑） */}
          {record.signStatus !== 'signed' && (
          <button 
            onClick={() => handleOpenModal(record)}
            className="p-1 hover:bg-gray-100 rounded text-gray-500"
            title="编辑"
          >
            <Edit className="w-3.5 h-3.5" />
          </button>
          )}
          {/* 删除（未签署且非生效状态才能删除） */}
          {record.signStatus !== 'signed' && record.status !== 'active' && (
            <button 
              onClick={() => handleDelete(record)}
              className="p-1 hover:bg-gray-100 rounded text-gray-500 hover:text-red-600"
              title="删除"
            >
              <Trash2 className="w-3.5 h-3.5" />
            </button>
          )}
        </div>
      )
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  ], [])

  const tabs = [
    { label: '仪表盘', path: '/crm' },
    { label: '客户管理', path: '/crm/customers' },
    { label: '销售机会', path: '/crm/opportunities' },
    { label: '报价管理', path: '/crm/quotations' },
    { label: '合同管理', path: '/crm/contracts' },
    { label: '客户反馈', path: '/crm/feedbacks' }
  ]

  return (
    <div className="p-4 space-y-4">
      <PageHeader
        title="CRM客户关系管理"
        tabs={tabs}
        activeTab="/crm/contracts"
        onTabChange={(path) => navigate(path)}
      />

      {/* 工具栏 */}
      <div className="flex items-center justify-between bg-white rounded-lg border border-gray-200 p-3">
        <div className="flex items-center gap-3">
          <div className="relative">
            <Search className="absolute left-2 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <input
              type="text"
              placeholder="搜索合同编号、名称、客户..."
              value={searchValue}
              onChange={(e) => setSearchValue(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && loadData()}
              className="pl-8 pr-3 py-1.5 text-xs border border-gray-200 rounded-lg w-64 focus:outline-none focus:ring-2 focus:ring-primary-500 bg-white"
            />
          </div>

          <select
            value={filterStatus}
            onChange={(e) => setFilterStatus(e.target.value)}
            className="px-3 py-1.5 text-xs border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 bg-white"
            title="筛选合同状态"
          >
            <option value="">全部状态</option>
            <option value="draft">草稿</option>
            <option value="pending">待签署</option>
            <option value="active">生效中</option>
            <option value="expired">已过期</option>
            <option value="terminated">已终止</option>
          </select>
        </div>

        <button
          onClick={() => handleOpenModal()}
          className="flex items-center gap-1 px-3 py-1.5 bg-primary-600 text-white text-xs rounded-lg hover:bg-primary-700"
        >
          <Plus className="w-4 h-4" />
          新建合同
        </button>
      </div>

      {/* 数据表格 */}
      <DataTable
        columns={columns}
        data={contracts}
        loading={loading}
        rowKey="id"
      />

      {/* 分页 */}
      {total > pageSize && (
        <div className="flex items-center justify-between bg-white rounded-lg border border-gray-200 px-4 py-3">
          <div className="text-xs text-gray-500">共 {total} 条记录</div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setPage(p => Math.max(1, p - 1))}
              disabled={page === 1}
              className="px-3 py-1 text-xs border rounded hover:bg-gray-50 disabled:opacity-50"
            >
              上一页
            </button>
            <button
              onClick={() => setPage(p => Math.min(Math.ceil(total / pageSize), p + 1))}
              disabled={page >= Math.ceil(total / pageSize)}
              className="px-3 py-1 text-xs border rounded hover:bg-gray-50 disabled:opacity-50"
            >
              下一页
            </button>
            <select
              value={pageSize}
              onChange={(e) => {
                setPageSize(Number(e.target.value))
                setPage(1)
              }}
              className="px-3 py-1.5 text-sm bg-white border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 text-gray-900"
              title="每页显示条数"
            >
              <option value={20}>20 条/页</option>
              <option value={50}>50 条/页</option>
              <option value={100}>100 条/页</option>
            </select>
          </div>
        </div>
      )}

      {/* 新增/编辑弹窗 */}
      {showModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg w-[600px] max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between p-4 border-b sticky top-0 bg-white">
              <h3 className="text-sm font-medium">{editingItem ? '编辑合同' : '新建合同'}</h3>
              <button onClick={() => setShowModal(false)} className="p-1 hover:bg-gray-100 rounded" title="关闭">
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="p-4 space-y-4">
              <div>
                <label className="block text-xs text-gray-600 mb-1">合同名称 *</label>
                <input
                  type="text"
                  value={formData.contractName}
                  onChange={(e) => setFormData({...formData, contractName: e.target.value})}
                  className="w-full px-3 py-2 text-xs border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 bg-white"
                  placeholder="请输入合同名称"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs text-gray-600 mb-1">客户 *</label>
                  <select
                    value={formData.customerId}
                    onChange={(e) => {
                      const customer = customers.find(c => c.id === e.target.value)
                      setFormData({
                        ...formData, 
                        customerId: e.target.value,
                        customerName: customer?.customerName || ''
                      })
                    }}
                    className="w-full px-3 py-2 text-xs border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 bg-white"
                    title="选择客户"
                  >
                    <option value="">请选择客户</option>
                    {customers.map(c => (
                      <option key={c.id} value={c.id}>{c.customerName}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-xs text-gray-600 mb-1">合同类型</label>
                  <select
                    value={formData.contractType}
                    onChange={(e) => setFormData({...formData, contractType: e.target.value})}
                    className="w-full px-3 py-2 text-xs border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 bg-white"
                    title="选择合同类型"
                  >
                    <option value="service">服务合同</option>
                    <option value="sales">销售合同</option>
                    <option value="purchase">采购合同</option>
                    <option value="cooperation">合作协议</option>
                    <option value="other">其他</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs text-gray-600 mb-1">合同金额</label>
                  <input
                    type="number"
                    value={formData.contractAmount}
                    onChange={(e) => setFormData({...formData, contractAmount: parseFloat(e.target.value) || 0})}
                    className="w-full px-3 py-2 text-xs border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 bg-white"
                    min="0"
                    step="0.01"
                    placeholder="请输入金额"
                  />
                </div>
                <div>
                  <label className="block text-xs text-gray-600 mb-1">币种</label>
                  <select
                    value={formData.currency}
                    onChange={(e) => setFormData({...formData, currency: e.target.value})}
                    className="w-full px-3 py-2 text-xs border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 bg-white"
                    title="选择币种"
                  >
                    <option value="CNY">人民币 (CNY)</option>
                    <option value="USD">美元 (USD)</option>
                    <option value="EUR">欧元 (EUR)</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-3 gap-4">
                <div>
                  <label className="block text-xs text-gray-600 mb-1">开始日期</label>
                  <DatePicker
                    value={formData.startDate}
                    onChange={(value) => setFormData({...formData, startDate: value})}
                    placeholder="选择开始日期"
                  />
                </div>
                <div>
                  <label className="block text-xs text-gray-600 mb-1">结束日期</label>
                  <DatePicker
                    value={formData.endDate}
                    onChange={(value) => setFormData({...formData, endDate: value})}
                    placeholder="选择结束日期"
                  />
                </div>
                <div>
                  <label className="block text-xs text-gray-600 mb-1">签署日期</label>
                  <DatePicker
                    value={formData.signDate}
                    onChange={(value) => setFormData({...formData, signDate: value})}
                    placeholder="选择签署日期"
                  />
                </div>
              </div>

              <div>
                <label className="block text-xs text-gray-600 mb-1">合同条款</label>
                <textarea
                  value={formData.terms}
                  onChange={(e) => setFormData({...formData, terms: e.target.value})}
                  className="w-full px-3 py-2 text-xs border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 bg-white resize-none"
                  rows={3}
                  placeholder="请输入合同主要条款"
                />
              </div>

              <div>
                <label className="block text-xs text-gray-600 mb-1">备注</label>
                <textarea
                  value={formData.notes}
                  onChange={(e) => setFormData({...formData, notes: e.target.value})}
                  className="w-full px-3 py-2 text-xs border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 bg-white resize-none"
                  rows={2}
                  placeholder="请输入备注信息"
                />
              </div>
            </div>

            <div className="flex justify-end gap-2 p-4 border-t sticky bottom-0 bg-white">
              <button
                onClick={() => setShowModal(false)}
                className="px-4 py-2 text-xs text-gray-600 border rounded-lg hover:bg-gray-50"
              >
                取消
              </button>
              <button
                onClick={handleSubmit}
                className="px-4 py-2 text-xs text-white bg-primary-600 rounded-lg hover:bg-primary-700"
              >
                确定
              </button>
            </div>
          </div>
        </div>
      )}

      {/* 上传签署合同弹窗 */}
      {showUploadModal && uploadingContract && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg w-[480px]">
            <div className="flex items-center justify-between p-4 border-b">
              <h3 className="text-sm font-medium">上传已签署合同</h3>
              <button onClick={() => setShowUploadModal(false)} className="p-1 hover:bg-gray-100 rounded" title="关闭">
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="p-4 space-y-4">
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
                <div className="text-sm font-medium text-blue-900 mb-1">合同信息</div>
                <div className="text-xs text-blue-700 space-y-1">
                  <div>合同编号：{uploadingContract.contractNumber}</div>
                  <div>合同名称：{uploadingContract.contractName}</div>
                  <div>客户：{uploadingContract.customerName}</div>
                </div>
              </div>

              <div className="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center">
                <input
                  ref={fileInputRef}
                  type="file"
                  accept=".pdf,.jpg,.jpeg,.png"
                  onChange={(e) => {
                    const file = e.target.files?.[0]
                    if (file) {
                      handleUploadSignedContract(file)
                    }
                  }}
                  className="hidden"
                />
                
                {uploading ? (
                  <div className="flex flex-col items-center gap-2">
                    <Loader2 className="w-8 h-8 text-primary-600 animate-spin" />
                    <span className="text-sm text-gray-600">上传中...</span>
                  </div>
                ) : (
                  <>
                    <Upload className="w-10 h-10 text-gray-400 mx-auto mb-2" />
                    <div className="text-sm text-gray-600 mb-1">点击上传已签署的合同文件</div>
                    <div className="text-xs text-gray-400">支持 PDF、JPG、PNG 格式</div>
                    <button
                      onClick={() => fileInputRef.current?.click()}
                      className="mt-4 px-4 py-2 bg-primary-600 text-white text-xs rounded-lg hover:bg-primary-700"
                    >
                      选择文件
                    </button>
                  </>
                )}
              </div>

              <div className="text-xs text-gray-500">
                <p>⚠️ 请上传已由双方签署的合同扫描件或照片</p>
                <p>⚠️ 上传后合同状态将变更为"已签署"，相关销售机会可以进行成交操作</p>
              </div>
            </div>

            <div className="flex justify-end gap-2 p-4 border-t">
              <button
                onClick={() => setShowUploadModal(false)}
                disabled={uploading}
                className="px-4 py-2 text-xs text-gray-600 border rounded-lg hover:bg-gray-50 disabled:opacity-50"
              >
                取消
              </button>
            </div>
          </div>
        </div>
      )}

      {/* 签署历史弹窗 */}
      {showHistoryModal && uploadingContract && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg w-[600px] max-h-[80vh] overflow-y-auto">
            <div className="flex items-center justify-between p-4 border-b sticky top-0 bg-white">
              <h3 className="text-sm font-medium">签署历史 - {uploadingContract.contractNumber}</h3>
              <button onClick={() => setShowHistoryModal(false)} className="p-1 hover:bg-gray-100 rounded" title="关闭">
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="p-4">
              {historyLoading ? (
                <div className="flex items-center justify-center py-8">
                  <Loader2 className="w-6 h-6 text-primary-600 animate-spin" />
                  <span className="ml-2 text-sm text-gray-600">加载中...</span>
                </div>
              ) : signHistory.length > 0 ? (
                <div className="space-y-3">
                  {signHistory.map((h) => (
                    <div key={h.id} className="border border-gray-200 rounded-lg p-3">
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-xs font-medium text-gray-900">{h.actionName}</span>
                        <span className="text-[10px] text-gray-400">
                          {new Date(h.createTime).toLocaleString('zh-CN')}
                        </span>
                      </div>
                      <div className="flex items-center gap-4 text-xs text-gray-600">
                        <span>操作人：{h.operatorName}</span>
                        {h.oldStatus && h.newStatus && (
                          <span>
                            状态：
                            <span className="text-gray-400">{h.oldStatus}</span>
                            {' → '}
                            <span className="text-primary-600">{h.newStatus}</span>
                          </span>
                        )}
                      </div>
                      {h.remark && (
                        <div className="mt-2 text-xs text-gray-500 bg-gray-50 p-2 rounded">
                          {h.remark}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-8 text-sm text-gray-500">
                  暂无签署历史记录
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

