-- 产品定价数据
-- 导出时间: 2025-12-20T23:34:05.223Z
-- 数据量: 5 条

INSERT INTO products (id, product_code, product_name, product_name_en, category, description, is_active, sort_order, created_by, created_at, updated_at) VALUES ('89d331c6-8306-4da3-b9fe-b752a5f37495', 'PRD0001', '清提派-超大件-一口价', 'Customs clearance, container pickup and delivery - oversized items - fixed price', '', '', 1, 0, NULL, '2025-12-19T18:50:10.835Z', '2025-12-19T18:50:10.835Z') ON CONFLICT (product_code) DO UPDATE SET product_name = EXCLUDED.product_name, product_name_en = EXCLUDED.product_name_en, category = EXCLUDED.category, description = EXCLUDED.description, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, created_by = EXCLUDED.created_by, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at;
INSERT INTO products (id, product_code, product_name, product_name_en, category, description, is_active, sort_order, created_by, created_at, updated_at) VALUES ('prod-003', 'CUSTOMS', '清关服务', 'Customs Clearance Service', 'customs', '提供进出口清关服务，包含报关、查验、放行等', 1, 3, 'admin', '2025-12-18T02:40:43.703Z', '2025-12-18T02:40:43.703Z') ON CONFLICT (product_code) DO UPDATE SET product_name = EXCLUDED.product_name, product_name_en = EXCLUDED.product_name_en, category = EXCLUDED.category, description = EXCLUDED.description, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, created_by = EXCLUDED.created_by, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at;
INSERT INTO products (id, product_code, product_name, product_name_en, category, description, is_active, sort_order, created_by, created_at, updated_at) VALUES ('prod-005', 'TRUCKING', '陆运配送服务', 'Trucking & Delivery Service', 'trucking', '提供欧洲境内陆运配送服务', 1, 5, 'admin', '2025-12-18T02:40:43.703Z', '2025-12-18T02:40:43.703Z') ON CONFLICT (product_code) DO UPDATE SET product_name = EXCLUDED.product_name, product_name_en = EXCLUDED.product_name_en, category = EXCLUDED.category, description = EXCLUDED.description, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, created_by = EXCLUDED.created_by, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at;
INSERT INTO products (id, product_code, product_name, product_name_en, category, description, is_active, sort_order, created_by, created_at, updated_at) VALUES ('prod-006', 'AIR-FREIGHT', '空运服务', 'Air Freight Service', 'air_freight', '提供空运服务，适合紧急或高价值货物', 1, 6, 'admin', '2025-12-18T02:40:43.703Z', '2025-12-18T02:40:43.703Z') ON CONFLICT (product_code) DO UPDATE SET product_name = EXCLUDED.product_name, product_name_en = EXCLUDED.product_name_en, category = EXCLUDED.category, description = EXCLUDED.description, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, created_by = EXCLUDED.created_by, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at;
INSERT INTO products (id, product_code, product_name, product_name_en, category, description, is_active, sort_order, created_by, created_at, updated_at) VALUES ('prod-007', 'RAIL-FREIGHT', '铁路运输服务', 'Rail Freight Service', 'rail_freight', '提供中欧铁路运输服务', 1, 7, 'admin', '2025-12-18T02:40:43.703Z', '2025-12-18T02:40:43.703Z') ON CONFLICT (product_code) DO UPDATE SET product_name = EXCLUDED.product_name, product_name_en = EXCLUDED.product_name_en, category = EXCLUDED.category, description = EXCLUDED.description, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, created_by = EXCLUDED.created_by, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at;
